using System;

namespace DeleteBoilerplate.DynamicRouting.Attributes
{
    [AttributeUsage(AttributeTargets.Method)]
    public class PageTypeRoutingAttribute : Attribute
    {
        public readonly string[] PageTypeClassName;

        /// <param name="pageTypeClassName">CMS Page Type Class Name, use PageType.CLASS_NAME autogenerated property</param>
        public PageTypeRoutingAttribute(params string[] pageTypeClassName)
        {
            PageTypeClassName = pageTypeClassName;
        }
    }
}