//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(SocialIcon.CLASS_NAME, typeof(SocialIcon))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
    /// <summary>
    /// Represents a content item of type SocialIcon.
    /// </summary>
    public partial class SocialIcon : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "DeleteBoilerplate.SocialIcon";


        /// <summary>
        /// The instance of the class that provides extended API for working with SocialIcon fields.
        /// </summary>
        private readonly SocialIconFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// SocialIconID.
        /// </summary>
        [DatabaseIDField]
        public int SocialIconID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SocialIconID"), 0);
            }
            set
            {
                SetValue("SocialIconID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Url"), @"");
            }
            set
            {
                SetValue("Url", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Image"), @"");
            }
            set
            {
                SetValue("Image", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with SocialIcon fields.
        /// </summary>
        [RegisterProperty]
        public SocialIconFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with SocialIcon fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class SocialIconFields : AbstractHierarchicalObject<SocialIconFields>
        {
            /// <summary>
            /// The content item of type SocialIcon that is a target of the extended API.
            /// </summary>
            private readonly SocialIcon mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="SocialIconFields" /> class with the specified content item of type SocialIcon.
            /// </summary>
            /// <param name="instance">The content item of type SocialIcon that is a target of the extended API.</param>
            public SocialIconFields(SocialIcon instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// SocialIconID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.SocialIconID;
                }
                set
                {
                    mInstance.SocialIconID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.Url;
                }
                set
                {
                    mInstance.Url = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.Image;
                }
                set
                {
                    mInstance.Image = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="SocialIcon" /> class.
        /// </summary>
        public SocialIcon() : base(CLASS_NAME)
        {
            mFields = new SocialIconFields(this);
        }

        #endregion
    }
}
