//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(GlobalConfiguration.CLASS_NAME, typeof(GlobalConfiguration))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
	/// <summary>
	/// Represents a content item of type GlobalConfiguration.
	/// </summary>
	public partial class GlobalConfiguration : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "DeleteBoilerplate.GlobalConfiguration";


		/// <summary>
		/// The instance of the class that provides extended API for working with GlobalConfiguration fields.
		/// </summary>
		private readonly GlobalConfigurationFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// GlobalConfigurationID.
		/// </summary>
		[DatabaseIDField]
		public int GlobalConfigurationID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("GlobalConfigurationID"), 0);
			}
			set
			{
				SetValue("GlobalConfigurationID", value);
			}
		}


		/// <summary>
		/// Image.
		/// </summary>
		[DatabaseField]
		public string Image
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Image"), @"");
			}
			set
			{
				SetValue("Image", value);
			}
		}


		/// <summary>
		/// Image Alt.
		/// </summary>
		[DatabaseField]
		public string ImageAlt
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ImageAlt"), @"");
			}
			set
			{
				SetValue("ImageAlt", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with GlobalConfiguration fields.
		/// </summary>
		[RegisterProperty]
		public GlobalConfigurationFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with GlobalConfiguration fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class GlobalConfigurationFields : AbstractHierarchicalObject<GlobalConfigurationFields>
		{
			/// <summary>
			/// The content item of type GlobalConfiguration that is a target of the extended API.
			/// </summary>
			private readonly GlobalConfiguration mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="GlobalConfigurationFields" /> class with the specified content item of type GlobalConfiguration.
			/// </summary>
			/// <param name="instance">The content item of type GlobalConfiguration that is a target of the extended API.</param>
			public GlobalConfigurationFields(GlobalConfiguration instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// GlobalConfigurationID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.GlobalConfigurationID;
				}
				set
				{
					mInstance.GlobalConfigurationID = value;
				}
			}


			/// <summary>
			/// Image.
			/// </summary>
			public string Image
			{
				get
				{
					return mInstance.Image;
				}
				set
				{
					mInstance.Image = value;
				}
			}


			/// <summary>
			/// Image Alt.
			/// </summary>
			public string ImageAlt
			{
				get
				{
					return mInstance.ImageAlt;
				}
				set
				{
					mInstance.ImageAlt = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="GlobalConfiguration" /> class.
		/// </summary>
		public GlobalConfiguration() : base(CLASS_NAME)
		{
			mFields = new GlobalConfigurationFields(this);
		}

		#endregion
	}
}