//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TaxonomyItem.CLASS_NAME, typeof(TaxonomyItem))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
    /// <summary>
    /// Represents a content item of type TaxonomyItem.
    /// </summary>
    public partial class TaxonomyItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "DeleteBoilerplate.TaxonomyItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with TaxonomyItem fields.
        /// </summary>
        private readonly TaxonomyItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// TaxonomyItemID.
        /// </summary>
        [DatabaseIDField]
        public int TaxonomyItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TaxonomyItemID"), 0);
            }
            set
            {
                SetValue("TaxonomyItemID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Code.
        /// </summary>
        [DatabaseField]
        public string Code
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Code"), @"");
            }
            set
            {
                SetValue("Code", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with TaxonomyItem fields.
        /// </summary>
        [RegisterProperty]
        public TaxonomyItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with TaxonomyItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class TaxonomyItemFields : AbstractHierarchicalObject<TaxonomyItemFields>
        {
            /// <summary>
            /// The content item of type TaxonomyItem that is a target of the extended API.
            /// </summary>
            private readonly TaxonomyItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="TaxonomyItemFields" /> class with the specified content item of type TaxonomyItem.
            /// </summary>
            /// <param name="instance">The content item of type TaxonomyItem that is a target of the extended API.</param>
            public TaxonomyItemFields(TaxonomyItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// TaxonomyItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.TaxonomyItemID;
                }
                set
                {
                    mInstance.TaxonomyItemID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Code.
            /// </summary>
            public string Code
            {
                get
                {
                    return mInstance.Code;
                }
                set
                {
                    mInstance.Code = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxonomyItem" /> class.
        /// </summary>
        public TaxonomyItem() : base(CLASS_NAME)
        {
            mFields = new TaxonomyItemFields(this);
        }

        #endregion
    }
}