//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(NavigationLink.CLASS_NAME, typeof(NavigationLink))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
    /// <summary>
    /// Represents a content item of type NavigationLink.
    /// </summary>
    public partial class NavigationLink : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "DeleteBoilerplate.NavigationLink";


        /// <summary>
        /// The instance of the class that provides extended API for working with NavigationLink fields.
        /// </summary>
        private readonly NavigationLinkFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// NavigationLinkID.
        /// </summary>
        [DatabaseIDField]
        public int NavigationLinkID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("NavigationLinkID"), 0);
            }
            set
            {
                SetValue("NavigationLinkID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Url"), @"");
            }
            set
            {
                SetValue("Url", value);
            }
        }


        /// <summary>
        /// Open in.
        /// </summary>
        [DatabaseField]
        public string Target
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Target"), @"_self");
            }
            set
            {
                SetValue("Target", value);
            }
        }


        /// <summary>
        /// Associated Page.
        /// </summary>
        [DatabaseField]
        public Guid AssociatedPage
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("AssociatedPage"), Guid.Empty);
            }
            set
            {
                SetValue("AssociatedPage", value);
            }
        }


        /// <summary>
        /// Active Color.
        /// </summary>
        [DatabaseField]
        public string ActiveColor
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ActiveColor"), @"");
            }
            set
            {
                SetValue("ActiveColor", value);
            }
        }


        /// <summary>
        /// Hide On Mobile.
        /// </summary>
        [DatabaseField]
        public bool HideOnMobile
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("HideOnMobile"), false);
            }
            set
            {
                SetValue("HideOnMobile", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with NavigationLink fields.
        /// </summary>
        [RegisterProperty]
        public NavigationLinkFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with NavigationLink fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class NavigationLinkFields : AbstractHierarchicalObject<NavigationLinkFields>
        {
            /// <summary>
            /// The content item of type NavigationLink that is a target of the extended API.
            /// </summary>
            private readonly NavigationLink mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="NavigationLinkFields" /> class with the specified content item of type NavigationLink.
            /// </summary>
            /// <param name="instance">The content item of type NavigationLink that is a target of the extended API.</param>
            public NavigationLinkFields(NavigationLink instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// NavigationLinkID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.NavigationLinkID;
                }
                set
                {
                    mInstance.NavigationLinkID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.Url;
                }
                set
                {
                    mInstance.Url = value;
                }
            }


            /// <summary>
            /// Open in.
            /// </summary>
            public string Target
            {
                get
                {
                    return mInstance.Target;
                }
                set
                {
                    mInstance.Target = value;
                }
            }


            /// <summary>
            /// Associated Page.
            /// </summary>
            public Guid AssociatedPage
            {
                get
                {
                    return mInstance.AssociatedPage;
                }
                set
                {
                    mInstance.AssociatedPage = value;
                }
            }


            /// <summary>
            /// Active Color.
            /// </summary>
            public string ActiveColor
            {
                get
                {
                    return mInstance.ActiveColor;
                }
                set
                {
                    mInstance.ActiveColor = value;
                }
            }


            /// <summary>
            /// Hide On Mobile.
            /// </summary>
            public bool HideOnMobile
            {
                get
                {
                    return mInstance.HideOnMobile;
                }
                set
                {
                    mInstance.HideOnMobile = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationLink" /> class.
        /// </summary>
        public NavigationLink() : base(CLASS_NAME)
        {
            mFields = new NavigationLinkFields(this);
        }

        #endregion
    }
}
