//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.DeleteBoilerplate;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(TaxonomyType.CLASS_NAME, typeof(TaxonomyType))]

namespace CMS.DocumentEngine.Types.DeleteBoilerplate
{
    /// <summary>
    /// Represents a content item of type TaxonomyType.
    /// </summary>
    public partial class TaxonomyType : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "DeleteBoilerplate.TaxonomyType";


        /// <summary>
        /// The instance of the class that provides extended API for working with TaxonomyType fields.
        /// </summary>
        private readonly TaxonomyTypeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// TaxonomyTypeID.
        /// </summary>
        [DatabaseIDField]
        public int TaxonomyTypeID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("TaxonomyTypeID"), 0);
            }
            set
            {
                SetValue("TaxonomyTypeID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Code.
        /// </summary>
        [DatabaseField]
        public string Code
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Code"), @"");
            }
            set
            {
                SetValue("Code", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with TaxonomyType fields.
        /// </summary>
        [RegisterProperty]
        public TaxonomyTypeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with TaxonomyType fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class TaxonomyTypeFields : AbstractHierarchicalObject<TaxonomyTypeFields>
        {
            /// <summary>
            /// The content item of type TaxonomyType that is a target of the extended API.
            /// </summary>
            private readonly TaxonomyType mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="TaxonomyTypeFields" /> class with the specified content item of type TaxonomyType.
            /// </summary>
            /// <param name="instance">The content item of type TaxonomyType that is a target of the extended API.</param>
            public TaxonomyTypeFields(TaxonomyType instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// TaxonomyTypeID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.TaxonomyTypeID;
                }
                set
                {
                    mInstance.TaxonomyTypeID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Code.
            /// </summary>
            public string Code
            {
                get
                {
                    return mInstance.Code;
                }
                set
                {
                    mInstance.Code = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxonomyType" /> class.
        /// </summary>
        public TaxonomyType() : base(CLASS_NAME)
        {
            mFields = new TaxonomyTypeFields(this);
        }

        #endregion
    }
}